
project_id = "tkrmpskyskudhvvyhgqd"

[functions.import-anilibria]
verify_jwt = false

[functions.import-anime]
verify_jwt = false

[functions.import-anime-with-videos]
verify_jwt = false

[functions.import-from-database-anime]
verify_jwt = false

[functions.sync-anime]
verify_jwt = false

[functions.auto-sync-anime]
verify_jwt = false

[functions.fetch-sample-video]
verify_jwt = false

[functions.schedule-sync]
verify_jwt = false
