// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkrmpskyskudhvvyhgqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrcm1wc2t5c2t1ZGh2dnloZ3FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MDEzMzMsImV4cCI6MjA1NjM3NzMzM30.2unkL4WVqVuxx2g5_WVHAbZI37T9MEQI4TcQkuULGFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);